import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  // Icônes supplémentaires disponibles dans CoreUI
  cilPlus,
  cilCart,
  cilBuilding,
  cilClock,
  cilMoney,
  cilWallet,
  cilBank,
  cilBarcode,
  cilQrCode,
  cilTruck,
  cilGift,
  cilBriefcase,
  cilClipboard,
  cilDataTransferDown,
  cilDataTransferUp,
  cilFilter,
  cilFilterX,
  cilFullscreen,
  cilFullscreenExit,
  cilFunctions,
  cilGroup,
  cilImage,
  cilIndustry,
  cilInfo,
  cilInput,
  cilInputPower,
  cilKeyboard,
  cilLaptop,
  cilLeaf,
  cilLink,
  cilLinkAlt,
  cilLinkBroken,
  cilListFilter,
  cilListRich,
  cilLockUnlocked,
  cilLoop,
  cilLoopCircular,
  cilMinus,
  cilMobile,
  cilMonitor,
  cilMoodBad,
  cilMoodGood,
  cilMoodVeryBad,
  cilMoodVeryGood,
  cilMove,
  cilMusicNote,
  cilObjectGroup,
  cilObjectUngroup,
  cilOpacity,
  cilPaint,
  cilPaintBucket,
  cilParagraph,
  cilPhone,
  cilPin,
  cilPlant,
  cilPlaylistAdd,
  cilPool,
  cilPowerStandby,
  cilPregnant,
  cilPushchair,
  cilRecycle,
  cilResizeBoth,
  cilResizeHeight,
  cilResizeWidth,
  cilRestaurant,
  cilRoom,
  cilRss,
  cilRuble,
  cilSchool,
  cilScreenDesktop,
  cilScreenSmartphone,
  cilSearch,
  cilSend,
  cilShareAlt,
  cilShieldAlt,
  cilShower,
  cilSmile,
  cilSmilePlus,
  cilSmoke,
  cilSmokingRoom,
  cilSoccer,
  cilSofa,
  cilSortAscending,
  cilSortDescending,
  cilSpeaker,
  cilStarHalf,
  cilStorage,
  cilStream,
  cilStrikethrough,
  cilSwapHorizontal,
  cilSwapVertical,
  cilSwimming,
  cilSync,
  cilTablet,
  cilTag,
  cilTaxi,
  cilTerminal,
  cilText,
  cilTextShapes,
  cilTextSize,
  cilTextSquare,
  cilThumbDown,
  cilThumbUp,
  cilToggleOff,
  cilToggleOn,
  cilToilet,
  cilTouchApp,
  cilUsb,
  cilUserPlus,
  cilUserX,
  cilVector,
  cilVideo,
  cilVideogame,
  cilViewColumn,
  cilViewModule,
  cilViewQuilt,
  cilViewStream,
  cilVoice,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilWalk,
  cilWallpaper,
  cilWarning,
  cilWatch,
  cilWc,
  cilWheelchair,
  cilWindow,
  cilWindowMaximize,
  cilWindowMinimize,
  cilWindowRestore,
  cilWrapText,
  cilX,
  cilXCircle,
  cilZoom,
  cilZoomIn,
  cilZoomOut
} from '@coreui/icons';

import { signet } from './signet';
import { logo } from './logo';

export const iconSubset = {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAccountLogout,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilContrast,
  cilCreditCard,
  cilCursor,
  cilDescription,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLanguage,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMediaRecord,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  // Icônes supplémentaires
  cilPlus,
  cilCart,
  cilBuilding,
  cilClock,
  cilMoney,
  cilWallet,
  cilBank,
  cilBarcode,
  cilQrCode,
  cilTruck,
  cilGift,
  cilBriefcase,
  cilClipboard,
  cilDataTransferDown,
  cilDataTransferUp,
  cilFilter,
  cilFilterX,
  cilFullscreen,
  cilFullscreenExit,
  cilFunctions,
  cilGroup,
  cilImage,
  cilIndustry,
  cilInfo,
  cilInput,
  cilInputPower,
  cilKeyboard,
  cilLaptop,
  cilLeaf,
  cilLink,
  cilLinkAlt,
  cilLinkBroken,
  cilListFilter,
  cilListRich,
  cilLockUnlocked,
  cilLoop,
  cilLoopCircular,
  cilMinus,
  cilMobile,
  cilMonitor,
  cilMoodBad,
  cilMoodGood,
  cilMoodVeryBad,
  cilMoodVeryGood,
  cilMove,
  cilMusicNote,
  cilObjectGroup,
  cilObjectUngroup,
  cilOpacity,
  cilPaint,
  cilPaintBucket,
  cilParagraph,
  cilPhone,
  cilPin,
  cilPlant,
  cilPlaylistAdd,
  cilPool,
  cilPowerStandby,
  cilPregnant,
  cilPushchair,
  cilRecycle,
  cilResizeBoth,
  cilResizeHeight,
  cilResizeWidth,
  cilRestaurant,
  cilRoom,
  cilRss,
  cilRuble,
  cilSchool,
  cilScreenDesktop,
  cilScreenSmartphone,
  cilSearch,
  cilSend,
  cilShareAlt,
  cilShieldAlt,
  cilShower,
  cilSmile,
  cilSmilePlus,
  cilSmoke,
  cilSmokingRoom,
  cilSoccer,
  cilSofa,
  cilSortAscending,
  cilSortDescending,
  cilSpeaker,
  cilStarHalf,
  cilStorage,
  cilStream,
  cilStrikethrough,
  cilSwapHorizontal,
  cilSwapVertical,
  cilSwimming,
  cilSync,
  cilTablet,
  cilTag,
  cilTaxi,
  cilTerminal,
  cilText,
  cilTextShapes,
  cilTextSize,
  cilTextSquare,
  cilThumbDown,
  cilThumbUp,
  cilToggleOff,
  cilToggleOn,
  cilToilet,
  cilTouchApp,
  cilUsb,
  cilUserPlus,
  cilUserX,
  cilVector,
  cilVideo,
  cilVideogame,
  cilViewColumn,
  cilViewModule,
  cilViewQuilt,
  cilViewStream,
  cilVoice,
  cilVolumeHigh,
  cilVolumeLow,
  cilVolumeOff,
  cilWalk,
  cilWallpaper,
  cilWarning,
  cilWatch,
  cilWc,
  cilWheelchair,
  cilWindow,
  cilWindowMaximize,
  cilWindowMinimize,
  cilWindowRestore,
  cilWrapText,
  cilX,
  cilXCircle,
  cilZoom,
  cilZoomIn,
  cilZoomOut,
  logo,
  signet
};

export enum IconSubset {
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cilAccountLogout = 'cilAccountLogout',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck = 'cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilContrast = 'cilContrast',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDescription = 'cilDescription',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFile = 'cilFile',
  cilGrid = 'cilGrid',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLanguage = 'cilLanguage',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMediaRecord = 'cilMediaRecord',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  // Icônes supplémentaires
  cilPlus = 'cilPlus',
  cilCart = 'cilCart',
  cilBuilding = 'cilBuilding',
  cilClock = 'cilClock',
  cilMoney = 'cilMoney',
  cilWallet = 'cilWallet',
  cilBank = 'cilBank',
  cilBarcode = 'cilBarcode',
  cilQrCode = 'cilQrCode',
  cilTruck = 'cilTruck',
  cilGift = 'cilGift',
  cilBriefcase = 'cilBriefcase',
  cilClipboard = 'cilClipboard',
  cilDataTransferDown = 'cilDataTransferDown',
  cilDataTransferUp = 'cilDataTransferUp',
  cilFilter = 'cilFilter',
  cilFilterX = 'cilFilterX',
  cilFullscreen = 'cilFullscreen',
  cilFullscreenExit = 'cilFullscreenExit',
  cilFunctions = 'cilFunctions',
  cilGroup = 'cilGroup',
  cilImage = 'cilImage',
  cilIndustry = 'cilIndustry',
  cilInfo = 'cilInfo',
  cilInput = 'cilInput',
  cilInputPower = 'cilInputPower',
  cilKeyboard = 'cilKeyboard',
  cilLaptop = 'cilLaptop',
  cilLeaf = 'cilLeaf',
  cilLink = 'cilLink',
  cilLinkAlt = 'cilLinkAlt',
  cilLinkBroken = 'cilLinkBroken',
  cilListFilter = 'cilListFilter',
  cilListRich = 'cilListRich',
  cilLockUnlocked = 'cilLockUnlocked',
  cilLoop = 'cilLoop',
  cilLoopCircular = 'cilLoopCircular',
  cilMinus = 'cilMinus',
  cilMobile = 'cilMobile',
  cilMonitor = 'cilMonitor',
  cilMoodBad = 'cilMoodBad',
  cilMoodGood = 'cilMoodGood',
  cilMoodVeryBad = 'cilMoodVeryBad',
  cilMoodVeryGood = 'cilMoodVeryGood',
  cilMove = 'cilMove',
  cilMusicNote = 'cilMusicNote',
  cilObjectGroup = 'cilObjectGroup',
  cilObjectUngroup = 'cilObjectUngroup',
  cilOpacity = 'cilOpacity',
  cilPaint = 'cilPaint',
  cilPaintBucket = 'cilPaintBucket',
  cilParagraph = 'cilParagraph',
  cilPhone = 'cilPhone',
  cilPin = 'cilPin',
  cilPlant = 'cilPlant',
  cilPlaylistAdd = 'cilPlaylistAdd',
  cilPool = 'cilPool',
  cilPowerStandby = 'cilPowerStandby',
  cilPregnant = 'cilPregnant',
  cilPushchair = 'cilPushchair',
  cilRecycle = 'cilRecycle',
  cilResizeBoth = 'cilResizeBoth',
  cilResizeHeight = 'cilResizeHeight',
  cilResizeWidth = 'cilResizeWidth',
  cilRestaurant = 'cilRestaurant',
  cilRoom = 'cilRoom',
  cilRss = 'cilRss',
  cilRuble = 'cilRuble',
  cilSchool = 'cilSchool',
  cilScreenDesktop = 'cilScreenDesktop',
  cilScreenSmartphone = 'cilScreenSmartphone',
  cilSearch = 'cilSearch',
  cilSend = 'cilSend',
  cilShareAlt = 'cilShareAlt',
  cilShieldAlt = 'cilShieldAlt',
  cilShower = 'cilShower',
  cilSmile = 'cilSmile',
  cilSmilePlus = 'cilSmilePlus',
  cilSmoke = 'cilSmoke',
  cilSmokingRoom = 'cilSmokingRoom',
  cilSoccer = 'cilSoccer',
  cilSofa = 'cilSofa',
  cilSortAscending = 'cilSortAscending',
  cilSortDescending = 'cilSortDescending',
  cilSpeaker = 'cilSpeaker',
  cilStarHalf = 'cilStarHalf',
  cilStorage = 'cilStorage',
  cilStream = 'cilStream',
  cilStrikethrough = 'cilStrikethrough',
  cilSwapHorizontal = 'cilSwapHorizontal',
  cilSwapVertical = 'cilSwapVertical',
  cilSwimming = 'cilSwimming',
  cilSync = 'cilSync',
  cilTablet = 'cilTablet',
  cilTag = 'cilTag',
  cilTaxi = 'cilTaxi',
  cilTerminal = 'cilTerminal',
  cilText = 'cilText',
  cilTextShapes = 'cilTextShapes',
  cilTextSize = 'cilTextSize',
  cilTextSquare = 'cilTextSquare',
  cilThumbDown = 'cilThumbDown',
  cilThumbUp = 'cilThumbUp',
  cilToggleOff = 'cilToggleOff',
  cilToggleOn = 'cilToggleOn',
  cilToilet = 'cilToilet',
  cilTouchApp = 'cilTouchApp',
  cilUsb = 'cilUsb',
  cilUserPlus = 'cilUserPlus',
  cilUserX = 'cilUserX',
  cilVector = 'cilVector',
  cilVideo = 'cilVideo',
  cilVideogame = 'cilVideogame',
  cilViewColumn = 'cilViewColumn',
  cilViewModule = 'cilViewModule',
  cilViewQuilt = 'cilViewQuilt',
  cilViewStream = 'cilViewStream',
  cilVoice = 'cilVoice',
  cilVolumeHigh = 'cilVolumeHigh',
  cilVolumeLow = 'cilVolumeLow',
  cilVolumeOff = 'cilVolumeOff',
  cilWalk = 'cilWalk',
  cilWallpaper = 'cilWallpaper',
  cilWarning = 'cilWarning',
  cilWatch = 'cilWatch',
  cilWc = 'cilWc',
  cilWheelchair = 'cilWheelchair',
  cilWindow = 'cilWindow',
  cilWindowMaximize = 'cilWindowMaximize',
  cilWindowMinimize = 'cilWindowMinimize',
  cilWindowRestore = 'cilWindowRestore',
  cilWrapText = 'cilWrapText',
  cilX = 'cilX',
  cilXCircle = 'cilXCircle',
  cilZoom = 'cilZoom',
  cilZoomIn = 'cilZoomIn',
  cilZoomOut = 'cilZoomOut',
  logo = 'logo',
  signet = 'signet'
}